version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  pre_build:
    commands:
      - echo "Running tests"
      # React projects usually need CI=true for test mode
      - CI=true npm test -- --watchAll=false

  build:
    commands:
      - echo "Building React app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
